http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h # 30 days

limiter:
  rps: 10
  burst: 20
  ttl: 10m

logger:
  level: debug

postgresql:
  ssl_mode: disable
  max_connections: 30
  min_connections: 10
  max_conn_idle_time: 5s
  max_conn_life_time: 10m
  health_check_period: 5s